name = "t4-stack"
compatibility_date = "2023-10-30"
send_metrics = false
node_compat = true
route = "t4-cwm.pages.dev/*"
workers_dev = false

[env.preview]
name = "t4-stack-preview"
workers_dev = true

[env.production]
name = "t4-stack"
workers_dev = false