name = "t4-test"
compatibility_date = "2023-10-30"
send_metrics = false
node_compat = true
route = "t4-cwm.pages.dev/*"
workers_dev = false



# name = "t4-test"

# compatibility_date = "2024-05-02"
# compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# route = "t4-cwm.pages.dev/*"
# workers_dev = false